; PróVisão · firmware V1.5
; Placa: ESP32-C3 Super Mini (USB-C)
; Compilar:  pio run
; Gravar:    pio run -t upload
; Monitor:   pio device monitor

[env:esp32c3_supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

; O Super Mini usa o USB nativo do C3 como porta serial:
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    adafruit/Adafruit_VL53L0X@^1.2.4
